"""
Embedded MVP content — fallback when PostgreSQL is unavailable
(Streamlit Community Cloud, local demo without Docker).
"""

from __future__ import annotations

# BEGIN AUTO:ENTITIES
ENTITIES = [
    {
        "id": "assurance",
        "name": "Mutualis Assurance",
        "domain_fr": "Assurance / sinistres",
        "domain_en": "Insurance / claims",
        "blurb_fr": "Contrats, sinistres, fraude, parcours digital assuré.",
        "blurb_en": "Policies, claims, fraud, digital policyholder journeys.",
    },
    {
        "id": "bank",
        "name": "Mutualis Bank",
        "domain_fr": "Banque / finance",
        "domain_en": "Banking / finance",
        "blurb_fr": "Compte, crédit, KYC, conformité et parcours client digital.",
        "blurb_en": "Accounts, credit, KYC, compliance and digital banking.",
    },
    {
        "id": "retail",
        "name": "Mutualis Retail",
        "domain_fr": "Retail / distribution",
        "domain_en": "Retail / distribution",
        "blurb_fr": "Magasins, e-commerce, caisse, assortiment et fidélité.",
        "blurb_en": "Stores, e-commerce, checkout, assortment and loyalty.",
    },
    {
        "id": "transport",
        "name": "Mutualis Transport",
        "domain_fr": "Transport / logistique",
        "domain_en": "Transport / logistics",
        "blurb_fr": "Flotte, tournées, tracking, entrepôts et délais de livraison.",
        "blurb_en": "Fleet, routes, tracking, warehouses and delivery SLAs.",
    },
    {
        "id": "energy",
        "name": "Mutualis Energy",
        "domain_fr": "Énergie / utilities",
        "domain_en": "Energy / utilities",
        "blurb_fr": "Compteurs, consommation, facturation et réseau.",
        "blurb_en": "Meters, consumption, billing and grid ops.",
    },
    {
        "id": "media",
        "name": "Mutualis Media",
        "domain_fr": "Média / audience",
        "domain_en": "Media / audience",
        "blurb_fr": "Contenus, audience, pub programmatique et mesures d'impact.",
        "blurb_en": "Content, audience, programmatic ads and impact measurement.",
    },
    {
        "id": "agro",
        "name": "Mutualis Agro",
        "domain_fr": "Agro / filière",
        "domain_en": "Agri / supply chain",
        "blurb_fr": "Filière agricole, traçabilité, stocks et coopératives.",
        "blurb_en": "Agri supply chain, traceability, stock and co-ops.",
    },
    {
        "id": "health",
        "name": "Mutualis Health",
        "domain_fr": "Santé / parcours patient",
        "domain_en": "Health / patient journeys",
        "blurb_fr": "Dossiers patients, parcours de soins, facturation et conformité santé.",
        "blurb_en": "Patient records, care pathways, billing and health compliance.",
    },
]
# END AUTO:ENTITIES

PROJECT_KINDS = [
    {
        "id": "it",
        "label_fr": "Projet IT",
        "label_en": "IT project",
        "hint_fr": "SI, CRM, ERP, infra, architecture, intégrations — Mutualis.",
        "hint_en": "Systems, CRM, ERP, infra, architecture, integrations — Mutualis.",
    },
    {
        "id": "data-ai",
        "label_fr": "Projet Data/IA",
        "label_en": "Data/AI project",
        "hint_fr": "Analytics, BI, ML, gouvernance data — Mutualis.",
        "hint_en": "Analytics, BI, ML, data governance — Mutualis.",
    },
]

ROLES = [
    {"id": "business-analyst", "label_fr": "Business Analyst", "label_en": "Business Analyst", "track": "pm"},
    {"id": "chef-de-projet", "label_fr": "Chef de projet", "label_en": "Project Manager", "track": "pm"},
    {"id": "product-owner", "label_fr": "Product Owner", "label_en": "Product Owner", "track": "pm"},
    {"id": "scrum-master", "label_fr": "Scrum Master", "label_en": "Scrum Master", "track": "pm"},
    {"id": "technico-fonctionnel", "label_fr": "Technico-fonctionnel", "label_en": "Techno-functional", "track": "pm"},
    {"id": "data-manager", "label_fr": "Data Manager", "label_en": "Data Manager", "track": "governance"},
    {"id": "data-steward", "label_fr": "Data Steward", "label_en": "Data Steward", "track": "governance"},
    {
        "id": "data-governance-manager",
        "label_fr": "Data Governance Manager",
        "label_en": "Data Governance Manager",
        "track": "governance",
    },
    {
        "id": "ai-governance-manager",
        "label_fr": "AI Governance Manager",
        "label_en": "AI Governance Manager",
        "track": "governance",
    },
]

CAREER_TITLES = [
    {"id": "junior", "label_fr": "Junior", "label_en": "Junior", "min_score": 0},
    {"id": "pm", "label_fr": "Confirmé", "label_en": "Mid-level", "min_score": 40},
    {"id": "senior", "label_fr": "Senior", "label_en": "Senior", "min_score": 100},
    {"id": "lead", "label_fr": "Lead", "label_en": "Lead", "min_score": 180},
    {"id": "head", "label_fr": "Head", "label_en": "Head", "min_score": 280},
]

LEVELS = [
    {
        "id": 0,
        "title_fr": "Onboarding Mutualis",
        "title_en": "Mutualis onboarding",
        "intro_fr": "Bienvenue. Premier Increment : cadrer le besoin et poser un livrable propre.",
        "intro_en": "Welcome. First Increment: frame the need and ship a clean deliverable.",
    },
    {
        "id": 1,
        "title_fr": "Qualité & risque",
        "title_en": "Quality & risk",
        "intro_fr": "Le COMEX regarde. Qualité des données, risques et arbitrages sous pression.",
        "intro_en": "The exec committee is watching. Data quality, risks and trade-offs under pressure.",
    },
]

STEPS = [
    {
        "id": "L0-S0",
        "level_id": 0,
        "sort_order": 0,
        "title_fr": "Cadrage du besoin",
        "title_en": "Frame the need",
        "say_fr": "Le métier veut « tout » pour hier. Il faut cadrer.",
        "say_en": "Business wants everything yesterday. You need to frame it.",
        "do_fr": "Rédige 3 critères d'acceptation testables pour la story prioritaire.",
        "do_en": "Write 3 testable acceptance criteria for the top story.",
        "expect_type": "text",
        "correction_fr": "Des critères chiffrés et testables (Given/When/Then ou checklist mesurable).",
        "correction_en": "Measurable, testable criteria (Given/When/Then or a measurable checklist).",
        "keywords": ["critere", "acceptation", "testable", "given", "when", "then", "mesure"],
    },
    {
        "id": "L0-S1",
        "level_id": 0,
        "sort_order": 1,
        "title_fr": "Premier script SQL",
        "title_en": "First SQL script",
        "say_fr": "Les volumes bruts sont sales. On te demande un SELECT de contrôle.",
        "say_en": "Raw volumes are messy. You need a control SELECT.",
        "do_fr": "Écris une requête SQL qui compte les lignes et filtre les NULL sur la clé métier.",
        "do_en": "Write a SQL query that counts rows and filters NULLs on the business key.",
        "expect_type": "sql",
        "correction_fr": "Un SELECT avec COUNT et un filtre IS NOT NULL (ou équivalent) sur la clé.",
        "correction_en": "A SELECT with COUNT and an IS NOT NULL filter (or equivalent) on the key.",
        "keywords": ["select", "count", "null", "where"],
    },
    {
        "id": "L1-S0",
        "level_id": 1,
        "sort_order": 0,
        "title_fr": "Risque de livraison",
        "title_en": "Delivery risk",
        "say_fr": "Le jalon glisse. Le sponsor pousse le scope.",
        "say_en": "The milestone is slipping. The sponsor pushes scope.",
        "do_fr": "Propose un arbitrage scope / délai / risque en 4–6 lignes.",
        "do_en": "Propose a scope / schedule / risk trade-off in 4–6 lines.",
        "expect_type": "text",
        "correction_fr": "Un arbitrage explicite : ce qui sort du scope, impact délai, risque résiduel.",
        "correction_en": "An explicit trade-off: what drops from scope, schedule impact, residual risk.",
        "keywords": ["scope", "delai", "risque", "jalon", "arbitrage"],
    },
    {
        "id": "L1-S1",
        "level_id": 1,
        "sort_order": 1,
        "title_fr": "Contrôle qualité Python",
        "title_en": "Python quality check",
        "say_fr": "Un CSV retail arrive avec des doublons. On attend un script de contrôle.",
        "say_en": "A retail CSV arrives with duplicates. A control script is expected.",
        "do_fr": "Écris un extrait Python (pandas) qui détecte les doublons sur une clé.",
        "do_en": "Write a Python (pandas) snippet that detects duplicates on a key.",
        "expect_type": "python",
        "correction_fr": "import/pandas + duplicated() ou drop_duplicates / value_counts sur la clé.",
        "correction_en": "import/pandas + duplicated() or drop_duplicates / value_counts on the key.",
        "keywords": ["import", "pandas", "duplicat", "drop_duplicates", "read_csv"],
    },
]

QUESTIONS = [
    {
        "step_id": "L0-S0",
        "kind": "pm",
        "question_fr": "Avant de coder, que fais-tu en priorité ?",
        "question_en": "Before coding, what do you do first?",
        "option_a_fr": "Lancer le développement pour montrer de la vélocité",
        "option_a_en": "Start development to show velocity",
        "option_b_fr": "Clarifier critères d'acceptation et impacts avec le métier",
        "option_b_en": "Clarify acceptance criteria and impacts with business",
        "option_c_fr": "Ajouter 10 stories pour couvrir tous les cas",
        "option_c_en": "Add 10 stories to cover every case",
        "correct_index": 1,
        "correction_fr": "Sans critères testables, la recette échoue et le fireRisk monte.",
        "correction_en": "Without testable criteria, UAT fails and fireRisk rises.",
        "framework_ref": "DoR",
    },
    {
        "step_id": "L0-S0",
        "kind": "gov",
        "question_fr": "Qui valide la définition du KPI « sinistre ouvert » (Mutualis Assurance) ou « séjour ouvert » (Mutualis Health) ?",
        "question_en": "Who validates the definition of the \"open claim\" KPI (Mutualis Assurance) or \"open stay\" (Mutualis Health)?",
        "option_a_fr": "Le développeur qui connaît la table",
        "option_a_en": "The developer who knows the table",
        "option_b_fr": "Le data steward / métier propriétaire de la donnée",
        "option_b_en": "The data steward / business data owner",
        "option_c_fr": "N'importe qui du COMEX",
        "option_c_en": "Anyone from the exec committee",
        "correct_index": 1,
        "correction_fr": "La définition métier appartient au steward / owner, pas au codeur seul — y compris en santé.",
        "correction_en": "The business definition belongs to the steward/owner, not the coder alone — including in health.",
        "framework_ref": "DAMA",
    },
    {
        "step_id": "L0-S1",
        "kind": "pm",
        "question_fr": "Le SELECT de contrôle échoue en revue. Que fais-tu ?",
        "question_en": "The control SELECT fails review. What do you do?",
        "option_a_fr": "Dire que « ça marche chez moi » et passer à autre chose",
        "option_a_en": "Say \"works on my machine\" and move on",
        "option_b_fr": "Documenter l'écart, corriger la requête, rejouer la revue",
        "option_b_en": "Document the gap, fix the query, re-run the review",
        "option_c_fr": "Masquer le problème jusqu'au COPIL",
        "option_c_en": "Hide the issue until the steering committee",
        "correct_index": 1,
        "correction_fr": "Transparence + correction + revalidation : posture PM saine.",
        "correction_en": "Transparency + fix + revalidation: healthy PM posture.",
        "framework_ref": "DoD",
    },
    {
        "step_id": "L0-S1",
        "kind": "gov",
        "question_fr": "Pourquoi filtrer les NULL sur la clé métier ?",
        "question_en": "Why filter NULLs on the business key?",
        "option_a_fr": "Pour que la requête soit plus courte",
        "option_a_en": "So the query is shorter",
        "option_b_fr": "Pour éviter de sous/surestimer les volumes et fausser les KPI",
        "option_b_en": "To avoid under/over-counting volumes and skewing KPIs",
        "option_c_fr": "Parce que PostgreSQL l'impose toujours",
        "option_c_en": "Because PostgreSQL always requires it",
        "correct_index": 1,
        "correction_fr": "Les NULL cassent jointures et agrégats → KPI faux.",
        "correction_en": "NULLs break joins and aggregates → wrong KPIs.",
        "framework_ref": "Data quality",
    },
    {
        "step_id": "L1-S0",
        "kind": "pm",
        "question_fr": "Le sponsor ajoute du scope sans bouger la date. Meilleure réaction ?",
        "question_en": "Sponsor adds scope without moving the date. Best reaction?",
        "option_a_fr": "Accepter tout pour « faire plaisir »",
        "option_a_en": "Accept everything to please them",
        "option_b_fr": "Arbitrer : ce qui entre, ce qui sort, risque résiduel écrit",
        "option_b_en": "Trade off: what comes in, what drops, residual risk written down",
        "option_c_fr": "Ignorer le sponsor",
        "option_c_en": "Ignore the sponsor",
        "correct_index": 1,
        "correction_fr": "Un arbitrage explicite protège le jalon et la confiance COMEX.",
        "correction_en": "An explicit trade-off protects the milestone and exec trust.",
        "framework_ref": "Risks",
    },
    {
        "step_id": "L1-S0",
        "kind": "gov",
        "question_fr": "Où enregistrer la décision d'arbitrage scope ?",
        "question_en": "Where should the scope trade-off decision be recorded?",
        "option_a_fr": "Uniquement à l'oral en daily",
        "option_a_en": "Only verbally in the daily",
        "option_b_fr": "Dans un ADR / compte-rendu accessible aux parties prenantes",
        "option_b_en": "In an ADR / minutes accessible to stakeholders",
        "option_c_fr": "Dans un Slack privé",
        "option_c_en": "In a private Slack thread",
        "correct_index": 1,
        "correction_fr": "Décision sans trace = rediscutée à chaque comité.",
        "correction_en": "Undocumented decisions get rediscussed in every meeting.",
        "framework_ref": "ADR",
    },
    {
        "step_id": "L1-S1",
        "kind": "pm",
        "question_fr": "Les doublons bloquent le KPI. Priorité ?",
        "question_en": "Duplicates block the KPI. Priority?",
        "option_a_fr": "Livrer le dashboard quand même",
        "option_a_en": "Ship the dashboard anyway",
        "option_b_fr": "Corriger la qualité (clé, dédoublonnage) avant publication",
        "option_b_en": "Fix quality (key, dedupe) before publishing",
        "option_c_fr": "Changer le KPI pour cacher le problème",
        "option_c_en": "Change the KPI to hide the problem",
        "correct_index": 1,
        "correction_fr": "Publier un KPI faux détruit la confiance plus qu'un retard.",
        "correction_en": "Publishing a wrong KPI destroys trust more than a delay.",
        "framework_ref": "DoD",
    },
    {
        "step_id": "L1-S1",
        "kind": "gov",
        "question_fr": "Qui doit être alerté si la règle de dédoublonnage change ?",
        "question_en": "Who must be notified if the dedupe rule changes?",
        "option_a_fr": "Personne : c'est technique",
        "option_a_en": "Nobody: it is technical",
        "option_b_fr": "Steward + consommateurs du KPI (métier / BI)",
        "option_b_en": "Steward + KPI consumers (business / BI)",
        "option_c_fr": "Uniquement le stagiaire data",
        "option_c_en": "Only the data intern",
        "correct_index": 1,
        "correction_fr": "Changement de règle = impact définition et usage : notifier les consommateurs.",
        "correction_en": "Rule change impacts definition and usage: notify consumers.",
        "framework_ref": "Data lineage",
    },
]

MEETING_FIRED = {
    "id": "comex-fired",
    "title_fr": "COMEX — Fin de mission",
    "title_en": "Exec — End of assignment",
    "opening_fr": "Le risque RH a atteint le seuil. Le COMEX clôt ta mission Mutualis.",
    "opening_en": "HR risk hit the threshold. The exec committee ends your Mutualis assignment.",
    "closing_fr": "Tu es sacké. Relance une partie pour retenter.",
    "closing_en": "You are sacked. Start a new game to try again.",
}

IT_ROLE_IDS = (
    "business-analyst",
    "chef-de-projet",
    "product-owner",
    "scrum-master",
    "technico-fonctionnel",
)
DATA_AI_ROLE_IDS = IT_ROLE_IDS + (
    "data-manager",
    "data-steward",
    "data-governance-manager",
    "ai-governance-manager",
)
