-- Auto-generated by scripts/sync_game_content.py — do not edit by hand
INSERT INTO entities (id, name, domain_fr, domain_en, blurb_fr, blurb_en) VALUES
  ('assurance', 'Mutualis Assurance', 'Assurance / sinistres', 'Insurance / claims', 'Contrats, sinistres, fraude, parcours digital assuré.', 'Policies, claims, fraud, digital policyholder journeys.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  domain_fr = EXCLUDED.domain_fr,
  domain_en = EXCLUDED.domain_en,
  blurb_fr = EXCLUDED.blurb_fr,
  blurb_en = EXCLUDED.blurb_en;
INSERT INTO entities (id, name, domain_fr, domain_en, blurb_fr, blurb_en) VALUES
  ('bank', 'Mutualis Bank', 'Banque / finance', 'Banking / finance', 'Compte, crédit, KYC, conformité et parcours client digital.', 'Accounts, credit, KYC, compliance and digital banking.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  domain_fr = EXCLUDED.domain_fr,
  domain_en = EXCLUDED.domain_en,
  blurb_fr = EXCLUDED.blurb_fr,
  blurb_en = EXCLUDED.blurb_en;
INSERT INTO entities (id, name, domain_fr, domain_en, blurb_fr, blurb_en) VALUES
  ('retail', 'Mutualis Retail', 'Retail / distribution', 'Retail / distribution', 'Magasins, e-commerce, caisse, assortiment et fidélité.', 'Stores, e-commerce, checkout, assortment and loyalty.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  domain_fr = EXCLUDED.domain_fr,
  domain_en = EXCLUDED.domain_en,
  blurb_fr = EXCLUDED.blurb_fr,
  blurb_en = EXCLUDED.blurb_en;
INSERT INTO entities (id, name, domain_fr, domain_en, blurb_fr, blurb_en) VALUES
  ('transport', 'Mutualis Transport', 'Transport / logistique', 'Transport / logistics', 'Flotte, tournées, tracking, entrepôts et délais de livraison.', 'Fleet, routes, tracking, warehouses and delivery SLAs.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  domain_fr = EXCLUDED.domain_fr,
  domain_en = EXCLUDED.domain_en,
  blurb_fr = EXCLUDED.blurb_fr,
  blurb_en = EXCLUDED.blurb_en;
INSERT INTO entities (id, name, domain_fr, domain_en, blurb_fr, blurb_en) VALUES
  ('energy', 'Mutualis Energy', 'Énergie / utilities', 'Energy / utilities', 'Compteurs, consommation, facturation et réseau.', 'Meters, consumption, billing and grid ops.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  domain_fr = EXCLUDED.domain_fr,
  domain_en = EXCLUDED.domain_en,
  blurb_fr = EXCLUDED.blurb_fr,
  blurb_en = EXCLUDED.blurb_en;
INSERT INTO entities (id, name, domain_fr, domain_en, blurb_fr, blurb_en) VALUES
  ('media', 'Mutualis Media', 'Média / audience', 'Media / audience', 'Contenus, audience, pub programmatique et mesures d''impact.', 'Content, audience, programmatic ads and impact measurement.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  domain_fr = EXCLUDED.domain_fr,
  domain_en = EXCLUDED.domain_en,
  blurb_fr = EXCLUDED.blurb_fr,
  blurb_en = EXCLUDED.blurb_en;
INSERT INTO entities (id, name, domain_fr, domain_en, blurb_fr, blurb_en) VALUES
  ('agro', 'Mutualis Agro', 'Agro / filière', 'Agri / supply chain', 'Filière agricole, traçabilité, stocks et coopératives.', 'Agri supply chain, traceability, stock and co-ops.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  domain_fr = EXCLUDED.domain_fr,
  domain_en = EXCLUDED.domain_en,
  blurb_fr = EXCLUDED.blurb_fr,
  blurb_en = EXCLUDED.blurb_en;
INSERT INTO entities (id, name, domain_fr, domain_en, blurb_fr, blurb_en) VALUES
  ('health', 'Mutualis Health', 'Santé / parcours patient', 'Health / patient journeys', 'Dossiers patients, parcours de soins, facturation et conformité santé.', 'Patient records, care pathways, billing and health compliance.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  domain_fr = EXCLUDED.domain_fr,
  domain_en = EXCLUDED.domain_en,
  blurb_fr = EXCLUDED.blurb_fr,
  blurb_en = EXCLUDED.blurb_en;
