/**
 * Export all game data tables from src/data/dataStack/*.ts → sql/seed_from_ts.sql
 *
 *   npx --yes tsx scripts/exportTsToSql.ts
 *
 * After this, PostgreSQL is the source of truth for content.
 */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { ADVENTURE_LEVELS } from '../src/data/dataStack/adventure'
import { PRACTICE_EXERCISES } from '../src/data/dataStack/exercises'
import { GAME_DATASETS } from '../src/data/dataStack/gameDatasets'
import { CURATED_GOVERNANCE_EN } from '../src/data/dataStack/governancePacks.en'
import { CURATED_GOVERNANCE } from '../src/data/dataStack/governancePacks'
import {
  COMEX_MEETINGS,
  COPIL_BANK,
  COPROJ_BANK,
  SCRUM_BANK,
} from '../src/data/dataStack/meetingBank'
import { MUTUALIS_ENTITIES } from '../src/data/dataStack/mutualisEntities'
import { HUMAN_BANK_EN, HUMAN_TWISTS_EN } from '../src/data/dataStack/pmHumanBank.en'
import { HUMAN_BANK_FR, HUMAN_TWISTS_FR } from '../src/data/dataStack/pmHumanBank'
import { CURATED_PM_EN } from '../src/data/dataStack/pmPacks.en'
import { CURATED_PM } from '../src/data/dataStack/pmPacks'
import {
  PROJECT_KINDS,
  rolesForProject,
  type ProjectKind,
} from '../src/data/dataStack/projectPaths'
import { PROFILES } from '../src/data/dataStack/roleContent'
import { ROLE_TOOL_STACKS } from '../src/data/dataStack/roleToolStacks'
import { allStoryKeys, roleStory } from '../src/data/dataStack/roleStories'
import { GUIDES_EN } from '../src/data/dataStack/toolOnboarding.en'
import { GUIDES as GUIDES_FR } from '../src/data/dataStack/toolOnboarding'
import {
  CODE_FOCUS_TOOLS,
  PHASE_LABELS,
  PHASE_LABELS_EN,
  PHASE_ORDER,
  STACK_TOOLS,
} from '../src/data/dataStack/tools'

const CAREER = [
  {
    id: 'junior',
    label_fr: 'Junior',
    label_en: 'Junior',
    min_score: 0,
    blurb_fr: 'Tu intègres la squad Mutualis. On te regarde.',
    blurb_en: 'You join the Mutualis squad. Eyes are on you.',
  },
  {
    id: 'pm',
    label_fr: 'Confirmé',
    label_en: 'Mid-level',
    min_score: 40,
    blurb_fr: 'Tu portes backlog, livrables et arbitrages métier.',
    blurb_en: 'You own backlog, deliverables and business trade-offs.',
  },
  {
    id: 'senior',
    label_fr: 'Senior',
    label_en: 'Senior',
    min_score: 100,
    blurb_fr: 'Tu sécurises les Increments sous pression COMEX.',
    blurb_en: 'You secure Increments under executive pressure.',
  },
  {
    id: 'lead',
    label_fr: 'Lead',
    label_en: 'Lead',
    min_score: 180,
    blurb_fr: "Tu fais grandir l'équipe et le système de delivery.",
    blurb_en: 'You grow the team and the delivery system.',
  },
  {
    id: 'head',
    label_fr: 'Head',
    label_en: 'Head',
    min_score: 280,
    blurb_fr: 'Tu incarnes la trajectoire Mutualis data & IA.',
    blurb_en: 'You embody Mutualis data & AI delivery.',
  },
] as const

// domain beats are not exported — import via casting helper file internals if needed
// We re-read from resolveExerciseCasting usage; export DOMAIN via mutualis by duplicating catalog sync

function esc(s: string): string {
  return s.replace(/'/g, "''")
}

function lit(s: string | null | undefined): string {
  if (s === null || s === undefined) return 'NULL'
  return `'${esc(String(s))}'`
}

function j(v: unknown): string {
  return `'${esc(JSON.stringify(v))}'::jsonb`
}

function arr(xs: string[] | undefined | null): string {
  if (!xs || xs.length === 0) return "'{}'"
  return `ARRAY[${xs.map((x) => lit(x)).join(', ')}]::text[]`
}

const lines: string[] = []
lines.push('-- AUTO-GENERATED by scripts/exportTsToSql.ts — do not edit by hand')
lines.push('-- Source: src/data/dataStack/*.ts')
lines.push('BEGIN;')
lines.push('')

// Truncate content tables (keep players)
const truncate = [
  'meeting_questions',
  'meetings',
  'step_questions',
  'adventure_steps',
  'adventure_levels',
  'content_packs',
  'role_tool_stacks',
  'entity_domain_beats',
  'game_datasets',
  'tools',
  'role_project_kinds',
  // don't truncate entities/roles if seeded — upsert instead
]
lines.push(`TRUNCATE ${truncate.join(', ')} RESTART IDENTITY CASCADE;`)
lines.push('')

// Career titles
lines.push('-- career_titles')
for (const t of CAREER) {
  lines.push(
    `INSERT INTO career_titles (id, label_fr, label_en, min_score, blurb_fr, blurb_en) VALUES (${lit(t.id)}, ${lit(t.label_fr)}, ${lit(t.label_en)}, ${t.min_score}, ${lit(t.blurb_fr)}, ${lit(t.blurb_en)}) ON CONFLICT (id) DO UPDATE SET label_fr=EXCLUDED.label_fr, label_en=EXCLUDED.label_en, min_score=EXCLUDED.min_score, blurb_fr=EXCLUDED.blurb_fr, blurb_en=EXCLUDED.blurb_en;`,
  )
}
lines.push('')

// Phases
lines.push('-- project_phases')
for (let i = 0; i < PHASE_ORDER.length; i++) {
  const id = PHASE_ORDER[i]!
  lines.push(
    `INSERT INTO project_phases (id, sort_order, label_fr, label_en) VALUES (${lit(id)}, ${i}, ${lit(PHASE_LABELS[id])}, ${lit(PHASE_LABELS_EN[id])}) ON CONFLICT (id) DO UPDATE SET sort_order=EXCLUDED.sort_order, label_fr=EXCLUDED.label_fr, label_en=EXCLUDED.label_en;`,
  )
}
lines.push('')

// Project kinds
lines.push('-- project_kinds')
for (const k of PROJECT_KINDS) {
  lines.push(
    `INSERT INTO project_kinds (id, label_fr, label_en, hint_fr, hint_en) VALUES (${lit(k.id)}, ${lit(k.label.fr)}, ${lit(k.label.en)}, ${lit(k.hint.fr)}, ${lit(k.hint.en)}) ON CONFLICT (id) DO UPDATE SET label_fr=EXCLUDED.label_fr, label_en=EXCLUDED.label_en, hint_fr=EXCLUDED.hint_fr, hint_en=EXCLUDED.hint_en;`,
  )
}
lines.push('')

// Entities
lines.push('-- entities')
for (const e of MUTUALIS_ENTITIES) {
  lines.push(
    `INSERT INTO entities (id, name, domain_fr, domain_en, blurb_fr, blurb_en) VALUES (${lit(e.id)}, ${lit(e.name)}, ${lit(e.domain.fr)}, ${lit(e.domain.en)}, ${lit(e.blurb.fr)}, ${lit(e.blurb.en)}) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, domain_fr=EXCLUDED.domain_fr, domain_en=EXCLUDED.domain_en, blurb_fr=EXCLUDED.blurb_fr, blurb_en=EXCLUDED.blurb_en;`,
  )
}
lines.push('')

// Roles + role_project_kinds
lines.push('-- roles')
const seenRoles = new Set<string>()
for (const kind of ['it', 'data-ai'] as ProjectKind[]) {
  for (const r of rolesForProject(kind)) {
    if (!seenRoles.has(r.id)) {
      seenRoles.add(r.id)
      const homeKind = r.track === 'governance' ? 'data-ai' : kind === 'it' ? 'it' : 'data-ai'
      // primary project_kind: governance → data-ai, else first seen
      lines.push(
        `INSERT INTO roles (id, label_fr, label_en, track, project_kind) VALUES (${lit(r.id)}, ${lit(r.label.fr)}, ${lit(r.label.en)}, ${lit(r.track)}, ${lit(homeKind)}) ON CONFLICT (id) DO UPDATE SET label_fr=EXCLUDED.label_fr, label_en=EXCLUDED.label_en, track=EXCLUDED.track;`,
      )
    }
    lines.push(
      `INSERT INTO role_project_kinds (role_id, project_kind) VALUES (${lit(r.id)}, ${lit(kind)}) ON CONFLICT DO NOTHING;`,
    )
  }
}
lines.push('')

// Tools
lines.push('-- tools')
const codeFocus = new Set(CODE_FOCUS_TOOLS)
for (const t of STACK_TOOLS) {
  lines.push(
    `INSERT INTO tools (id, name, category, phase, sort_order, blurb_fr, blurb_en, practice_focus, unlock_after, code_focus) VALUES (${lit(t.id)}, ${lit(t.name)}, ${lit(t.category)}, ${lit(t.phase)}, ${t.order}, ${lit(t.blurb)}, ${lit(t.blurb)}, ${arr(t.practiceFocus)}, ${arr(t.unlockAfter ?? [])}, ${codeFocus.has(t.id)}) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, phase=EXCLUDED.phase, sort_order=EXCLUDED.sort_order, blurb_fr=EXCLUDED.blurb_fr, practice_focus=EXCLUDED.practice_focus, unlock_after=EXCLUDED.unlock_after, code_focus=EXCLUDED.code_focus;`,
  )
}
lines.push('')

// Role tool stacks
lines.push('-- role_tool_stacks')
for (const [key, stack] of Object.entries(ROLE_TOOL_STACKS)) {
  if (!stack) continue
  const [projectKind, roleId] = key.split('__') as [string, string]
  stack.forEach((t, i) => {
    lines.push(
      `INSERT INTO role_tool_stacks (project_kind, role_id, tool_id, sort_order, market_id) VALUES (${lit(projectKind)}, ${lit(roleId)}, ${lit(t.id)}, ${i}, ${lit(t.id)}) ON CONFLICT DO NOTHING;`,
    )
  })
}
lines.push('')

// Datasets
lines.push('-- game_datasets')
for (const [id, ds] of Object.entries(GAME_DATASETS)) {
  lines.push(
    `INSERT INTO game_datasets (id, href, label, hint_fr, hint_en, source) VALUES (${lit(id)}, ${lit(ds.href)}, ${lit(ds.label)}, ${lit(ds.hint)}, ${lit(ds.hint)}, ${lit(ds.source)}) ON CONFLICT (id) DO UPDATE SET href=EXCLUDED.href, label=EXCLUDED.label, hint_fr=EXCLUDED.hint_fr, source=EXCLUDED.source;`,
  )
}
lines.push('')

// Adventure levels + steps (FR payloads; EN mirrored as FR until full i18n export)
lines.push('-- adventure_levels / steps')
ADVENTURE_LEVELS.forEach((level) => {
  lines.push(
    `INSERT INTO adventure_levels (id, title_fr, title_en, intro_fr, intro_en, phase, tools, payload_fr, payload_en) VALUES (${level.id}, ${lit(level.title)}, ${lit(level.title)}, ${lit(level.intro)}, ${lit(level.intro)}, ${lit(level.phase)}, ${arr(level.tools)}, ${j(level)}, ${j(level)}) ON CONFLICT (id) DO UPDATE SET title_fr=EXCLUDED.title_fr, intro_fr=EXCLUDED.intro_fr, phase=EXCLUDED.phase, tools=EXCLUDED.tools, payload_fr=EXCLUDED.payload_fr, payload_en=EXCLUDED.payload_en;`,
  )
  level.steps.forEach((step, idx) => {
    const expect = step.expect ?? 'text'
    const keywords = step.validate?.keywords ?? []
    lines.push(
      `INSERT INTO adventure_steps (id, level_id, sort_order, title_fr, title_en, say_fr, say_en, do_fr, do_en, expect_type, correction_fr, correction_en, keywords, tool_id, phase, payload_fr, payload_en) VALUES (${lit(step.id)}, ${level.id}, ${idx}, ${lit(step.title)}, ${lit(step.title)}, ${lit(step.say)}, ${lit(step.say)}, ${lit(step.do)}, ${lit(step.do)}, ${lit(expect)}, ${lit(step.correction)}, ${lit(step.correction)}, ${arr(keywords)}, ${lit(step.tool ?? null)}, ${lit(step.phase ?? null)}, ${j(step)}, ${j(step)}) ON CONFLICT (id) DO UPDATE SET level_id=EXCLUDED.level_id, sort_order=EXCLUDED.sort_order, title_fr=EXCLUDED.title_fr, say_fr=EXCLUDED.say_fr, do_fr=EXCLUDED.do_fr, expect_type=EXCLUDED.expect_type, correction_fr=EXCLUDED.correction_fr, keywords=EXCLUDED.keywords, tool_id=EXCLUDED.tool_id, phase=EXCLUDED.phase, payload_fr=EXCLUDED.payload_fr;`,
    )
    if (step.projectMgmt) {
      const pm = step.projectMgmt
      lines.push(
        `INSERT INTO step_questions (step_id, kind, question_fr, question_en, option_a_fr, option_a_en, option_b_fr, option_b_en, option_c_fr, option_c_en, correct_index, correction_fr, correction_en, framework_ref, payload_fr, payload_en) VALUES (${lit(step.id)}, 'pm', ${lit(pm.question)}, ${lit(pm.question)}, ${lit(pm.options[0])}, ${lit(pm.options[0])}, ${lit(pm.options[1])}, ${lit(pm.options[1])}, ${lit(pm.options[2])}, ${lit(pm.options[2])}, ${pm.correctIndex}, ${lit(pm.correction)}, ${lit(pm.correction)}, ${lit(pm.frameworkRef)}, ${j(pm)}, ${j(pm)});`,
      )
    }
    if (step.governance) {
      const g = step.governance
      lines.push(
        `INSERT INTO step_questions (step_id, kind, question_fr, question_en, option_a_fr, option_a_en, option_b_fr, option_b_en, option_c_fr, option_c_en, correct_index, correction_fr, correction_en, framework_ref, payload_fr, payload_en) VALUES (${lit(step.id)}, 'gov', ${lit(g.question)}, ${lit(g.question)}, ${lit(g.options[0])}, ${lit(g.options[0])}, ${lit(g.options[1])}, ${lit(g.options[1])}, ${lit(g.options[2])}, ${lit(g.options[2])}, ${g.correctIndex}, ${lit(g.correction)}, ${lit(g.correction)}, ${lit(g.damaRef)}, ${j(g)}, ${j(g)});`,
      )
    }
  })
})
lines.push('')

function pack(packType: string, itemKey: string, locale: string, payload: unknown, sort = 0) {
  lines.push(
    `INSERT INTO content_packs (pack_type, item_key, locale, sort_order, payload) VALUES (${lit(packType)}, ${lit(itemKey)}, ${lit(locale)}, ${sort}, ${j(payload)}) ON CONFLICT (pack_type, item_key, locale) DO UPDATE SET payload=EXCLUDED.payload, sort_order=EXCLUDED.sort_order;`,
  )
}

lines.push('-- content_packs: pm / gov curated')
for (const [k, v] of Object.entries(CURATED_PM)) pack('pm_curated', k, 'fr', v)
for (const [k, v] of Object.entries(CURATED_PM_EN)) pack('pm_curated', k, 'en', v)
for (const [k, v] of Object.entries(CURATED_GOVERNANCE)) pack('gov_curated', k, 'fr', v)
for (const [k, v] of Object.entries(CURATED_GOVERNANCE_EN)) pack('gov_curated', k, 'en', v)

lines.push('-- content_packs: human bank')
HUMAN_BANK_FR.forEach((v, i) => pack('pm_human', `fr-${i}`, 'fr', v, i))
HUMAN_BANK_EN.forEach((v, i) => pack('pm_human', `en-${i}`, 'en', v, i))
HUMAN_TWISTS_FR.forEach((v, i) => pack('pm_human_twist', `fr-${i}`, 'fr', { text: v }, i))
HUMAN_TWISTS_EN.forEach((v, i) => pack('pm_human_twist', `en-${i}`, 'en', { text: v }, i))

lines.push('-- content_packs: practice exercises')
PRACTICE_EXERCISES.forEach((ex, i) => pack('practice_exercise', ex.id, 'fr', ex, i))

lines.push('-- content_packs: tool onboarding')
for (const [toolId, guide] of Object.entries(GUIDES_FR)) pack('tool_onboarding', toolId, 'fr', guide)
for (const [toolId, guide] of Object.entries(GUIDES_EN)) pack('tool_onboarding', toolId, 'en', guide)

lines.push('-- content_packs: role stories + profiles')
for (const key of allStoryKeys()) {
  pack('role_story', key, 'fr', roleStory(key, 'fr'))
  pack('role_story', key, 'en', roleStory(key, 'en'))
}
for (const [roleId, profile] of Object.entries(PROFILES)) {
  pack('role_profile', roleId, 'fr', profile)
  pack('role_profile', roleId, 'en', profile)
}

// Meetings
lines.push('-- meetings')
function upsertMeeting(id: string, m: (typeof COPROJ_BANK)[number], localePair: 'fr') {
  void localePair
  lines.push(
    `INSERT INTO meetings (id, kind, title_fr, title_en, opening_fr, opening_en, closing_fr, closing_en, payload_fr, payload_en) VALUES (${lit(id)}, ${lit(m.kind)}, ${lit(m.title)}, ${lit(m.title)}, ${lit(m.opening)}, ${lit(m.opening)}, ${lit(m.closing)}, ${lit(m.closing)}, ${j(m)}, ${j(m)}) ON CONFLICT (id) DO UPDATE SET kind=EXCLUDED.kind, title_fr=EXCLUDED.title_fr, opening_fr=EXCLUDED.opening_fr, closing_fr=EXCLUDED.closing_fr, payload_fr=EXCLUDED.payload_fr;`,
  )
  m.questions.forEach((q, i) => {
    lines.push(
      `INSERT INTO meeting_questions (meeting_id, sort_order, npc_line_fr, npc_line_en, question_fr, question_en, option_a_fr, option_a_en, option_b_fr, option_b_en, option_c_fr, option_c_en, correct_index, correction_fr, correction_en, fire_risk_delta) VALUES (${lit(id)}, ${i}, ${lit(q.npcLine)}, ${lit(q.npcLine)}, ${lit(q.question)}, ${lit(q.question)}, ${lit(q.options[0])}, ${lit(q.options[0])}, ${lit(q.options[1])}, ${lit(q.options[1])}, ${lit(q.options[2])}, ${lit(q.options[2])}, ${q.correctIndex}, ${lit(q.correction)}, ${lit(q.correction)}, ${q.fireRiskDelta ?? 0}) ON CONFLICT (meeting_id, sort_order) DO UPDATE SET npc_line_fr=EXCLUDED.npc_line_fr, question_fr=EXCLUDED.question_fr, option_a_fr=EXCLUDED.option_a_fr, option_b_fr=EXCLUDED.option_b_fr, option_c_fr=EXCLUDED.option_c_fr, correct_index=EXCLUDED.correct_index, correction_fr=EXCLUDED.correction_fr, fire_risk_delta=EXCLUDED.fire_risk_delta;`,
    )
  })
}

COPROJ_BANK.forEach((m, i) => upsertMeeting(`coproj-${i + 1}`, m, 'fr'))
COPIL_BANK.forEach((m, i) => upsertMeeting(`copil-${i + 1}`, m, 'fr'))
SCRUM_BANK.forEach((m, i) => upsertMeeting(`scrum-${m.kind}-${i + 1}`, m, 'fr'))
for (const [key, m] of Object.entries(COMEX_MEETINGS)) {
  upsertMeeting(`comex-${key}`, m, 'fr')
}

lines.push('')
lines.push('COMMIT;')

const out = resolve('sql/seed_from_ts.sql')
writeFileSync(out, lines.join('\n'), 'utf8')
console.log(`Wrote ${out} (${lines.length} lines)`)
