#!/usr/bin/env node
/**
 * Monthly code-quality scan for Sack Me!
 * Writes markdown to stdout (and optionally QUALITY_REPORT_PATH).
 *
 * Focus: app/UI spaghetti (pages, components, hooks, lib) — not content banks.
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

const ROOT = process.cwd()
const SOFT = 300
const HARD = 800
const SCAN_ROOTS = ['src/pages', 'src/components', 'src/hooks', 'src/lib', 'src/i18n']
const SKIP_DIR = new Set(['node_modules', 'dist', '.git'])

/** Content dumps — listed separately, not treated as spaghetti. */
const CONTENT_GLOBS_PREFIX = 'src/data/dataStack/'

function walk(dir, out = []) {
  let entries
  try {
    entries = readdirSync(dir, { withFileTypes: true })
  } catch {
    return out
  }
  for (const ent of entries) {
    if (SKIP_DIR.has(ent.name)) continue
    const full = join(dir, ent.name)
    if (ent.isDirectory()) {
      walk(full, out)
      continue
    }
    if (!/\.(ts|tsx)$/.test(ent.name)) continue
    if (ent.name.endsWith('.test.ts') || ent.name.endsWith('.test.tsx')) continue
    out.push(full)
  }
  return out
}

function lineCount(path) {
  const text = readFileSync(path, 'utf8')
  if (!text) return 0
  return text.split(/\r?\n/).length
}

function collectTodoHits(path) {
  const text = readFileSync(path, 'utf8')
  const hits = []
  const lines = text.split(/\r?\n/)
  for (let i = 0; i < lines.length; i++) {
    if (/\b(TODO|FIXME|HACK|XXX)\b/.test(lines[i])) {
      hits.push({ line: i + 1, text: lines[i].trim().slice(0, 120) })
    }
  }
  return hits
}

function rel(path) {
  return relative(ROOT, path).replace(/\\/g, '/')
}

const appFiles = []
for (const root of SCAN_ROOTS) {
  walk(join(ROOT, root), appFiles)
}

const sized = appFiles
  .map((p) => ({ path: rel(p), lines: lineCount(p) }))
  .sort((a, b) => b.lines - a.lines)

const soft = sized.filter((f) => f.lines >= SOFT && f.lines < HARD)
const hard = sized.filter((f) => f.lines >= HARD)

const todos = []
for (const p of appFiles) {
  for (const hit of collectTodoHits(p)) {
    todos.push({ path: rel(p), ...hit })
  }
}

let contentSized = []
try {
  const contentFiles = walk(join(ROOT, CONTENT_GLOBS_PREFIX))
  contentSized = contentFiles
    .map((p) => ({ path: rel(p), lines: lineCount(p) }))
    .filter((f) => f.lines >= HARD)
    .sort((a, b) => b.lines - a.lines)
    .slice(0, 8)
} catch {
  /* optional */
}

const month = new Date().toISOString().slice(0, 7)
const lines = []

lines.push(`# Monthly quality review — ${month}`)
lines.push('')
lines.push('Automated scan of app/UI TypeScript (pages, components, hooks, lib, i18n).')
lines.push('Content banks under `src/data/dataStack/` are listed only when huge (not spaghetti).')
lines.push('')
lines.push('## Thresholds')
lines.push(`- Soft warn: ≥ ${SOFT} lines`)
lines.push(`- Hard flag: ≥ ${HARD} lines`)
lines.push('')
lines.push('## Hard flags (refactor priority)')
if (hard.length === 0) {
  lines.push('_None._')
} else {
  for (const f of hard) lines.push(`- \`${f.path}\` — **${f.lines}** lines`)
}
lines.push('')
lines.push('## Soft warnings')
if (soft.length === 0) {
  lines.push('_None._')
} else {
  for (const f of soft) lines.push(`- \`${f.path}\` — ${f.lines} lines`)
}
lines.push('')
lines.push('## Suggested next wave (checklist)')
lines.push('- [ ] Extract `useMeetingFlow` from `DataStackPage` (meeting state + COMEX close)')
lines.push('- [ ] Extract `useAdventureNav` (goBack / goForward / browseForward / advanceAfterPass)')
lines.push('- [ ] Extract `usePlayForm` / draft hydrate if form state still dominates the page')
lines.push('- [ ] Move remaining inline locale branches into `pmGameUi.ts`')
lines.push('- [ ] Keep English-only code comments; bilingual only in game content fields')
lines.push('- [ ] Run `npm test` + `npm run build` after each extraction')
lines.push('')
lines.push('## TODO / FIXME markers in app code')
if (todos.length === 0) {
  lines.push('_None._')
} else {
  for (const t of todos.slice(0, 40)) {
    lines.push(`- \`${t.path}:${t.line}\` — ${t.text}`)
  }
  if (todos.length > 40) lines.push(`- …and ${todos.length - 40} more`)
}
lines.push('')
lines.push('## Largest content banks (informational)')
if (contentSized.length === 0) {
  lines.push('_None over hard threshold, or folder missing._')
} else {
  for (const f of contentSized) lines.push(`- \`${f.path}\` — ${f.lines} lines`)
}
lines.push('')
lines.push('## Top 15 app files by size')
for (const f of sized.slice(0, 15)) {
  lines.push(`- \`${f.path}\` — ${f.lines}`)
}
lines.push('')
lines.push('_Generated by `node scripts/monthlyQualityReport.mjs`._')

const md = lines.join('\n')
process.stdout.write(md + '\n')

const outPath = process.env.QUALITY_REPORT_PATH
if (outPath) {
  writeFileSync(outPath, md, 'utf8')
}

const summary = {
  month,
  hard: hard.length,
  soft: soft.length,
  todos: todos.length,
  worst: hard[0]?.path ?? soft[0]?.path ?? null,
  worstLines: hard[0]?.lines ?? soft[0]?.lines ?? 0,
}
const sumPath = process.env.QUALITY_SUMMARY_PATH
if (sumPath) {
  writeFileSync(sumPath, JSON.stringify(summary, null, 2), 'utf8')
}

// Non-zero exit if hard flags exist (CI can still open the issue; job can continue-on-error)
if (process.env.QUALITY_FAIL_ON_HARD === '1' && hard.length > 0) {
  process.exitCode = 2
}
